//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimeSheetMSSQLBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthToken
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string access_token { get; set; }
        public string token_type { get; set; }
        public int expires_in { get; set; }
        public string username { get; set; }
        public System.DateTime issued { get; set; }
        public System.DateTime expires { get; set; }
        public string error { get; set; }
        public string error_description { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
