//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimeSheetMSSQLBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLogEntry
    {
        public int ID { get; set; }
        public decimal Hours { get; set; }
        public int EmployeeID { get; set; }
        public int WorkItemID { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    }
}
