//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimeSheetMSSQLBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.TimeLogEntries = new HashSet<TimeLogEntry>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Estimate { get; set; }
        public string UserID { get; set; }
        public int SupervisorID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeLogEntry> TimeLogEntries { get; set; }
        public virtual WorkItemStatu WorkItemStatu { get; set; }
        public virtual WorkItemType WorkItemType { get; set; }
    }
}
